#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ bundle exec jekyll serve --config _config.yml,_config_dev.yml

# Your web site url. eg: http://mysite.com
# Used to generate absolute links in feeds
# do not use for internal links (see baseurl comments)
# NO trailing slash
url: "http://0.0.0.0:4000"

# Your web site relative path from domain. eg: /folder
# Used to generate links. eg: <a href="{{ site.baseurl }}/blog/">Blog</a>
# or for resources <script src="{{ site.baseurl }}/js/js.js"></script>
# NO trailing slash
baseurl: "/website"

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  sourcemap: true

# Disable when not in production
google_analytics_tracking_id:

#############################################
# Assets configuration
#############################################

# extensionless url allows to automatically switch
# to current page protocol (http or https)
# to avoid mixed content problems
# distant-assets-url: "//swcarpentry.github.io/styles/"

# repository url
# NO TRAILING SLASH
distantAssetsUrl: "http://swctasks.github.io"

# path : "/styles"
# NO TRAILING SLASH
# Leave empty if assets are at the root of the domain
distantAssetsPath: "/styles/assets"

exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - Makefile
    - _posts/2015 # ignoring some posts to speed build in dev
    - _posts/2014
    - _posts/2013
    - _posts/2012
    - _posts/2011
    - _posts/2010
    - _posts/2009
    - _posts/2008
    - _posts/2007
    - _posts/2006

